baseURL = "https://blog.jqiu.io"
languageCode = "en-US"
title = "Jing's memo"
theme = "hemingway2"

keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/jingqiuELE"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
